In [1]:
import pandas as pd

In [2]:
items = {'Alice': pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants']),
         'Bob': pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch'])}

In [3]:
print(type(items))

<class 'dict'>

In [6]:
shop_cart = pd.DataFrame(items)

In [7]:
shop_cart

         Alice    Bob
bike     500.0  245.0
book      40.0    NaN
glasses  110.0    NaN
pants     45.0   25.0
watch      NaN   55.0

In [8]:
data = {'Alice': pd.Series([40, 110, 500, 45]),
        'Bob': pd.Series([245, 25, 55])}

In [10]:
view_data = pd.DataFrame(data)

In [11]:
view_data

   Alice    Bob
0     40  245.0
1    110   25.0
2    500   55.0
3     45    NaN

In [12]:
view_data.shape

(4, 2)

In [13]:
view_data.ndim

2

In [14]:
view_data.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
view_data.size

8

In [17]:
view_data.columns

Index(['Alice', 'Bob'], dtype='object')

In [19]:
bob_cart = pd.DataFrame(data, columns=['Bob'])

In [20]:
bob_cart

   Bob
0  245
1   25
2   55

In [21]:
selec_cart = pd.DataFrame(items, index=['bike', 'book'])

In [22]:
selec_cart

      Alice    Bob
bike    500  245.0
book     40    NaN

In [24]:
alice_cart = pd.DataFrame(items, index=['bike', 'book'], columns=['Alice'])

In [25]:
alice_cart

      Alice
bike    500
book     40

In [31]:
data_without_index = {'Floats': [4.5, 8.2, 9.6], 'Integers': [1, 2, 3]}

In [33]:
add_label = pd.DataFrame(data_without_index, index=['First', 'Second', 'Third'])

In [34]:
add_label

        Floats  Integers
First      4.5         1
Second     8.2         2
Third      9.6         3

In [35]:
items2 = [{'bikes': 20, 'pants': 30, 'watches': 35}, {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}]

In [36]:
store = pd.DataFrame(items2, index=['store1', 'store2'])

In [37]:
store

        bikes  pants  watches  glasses
store1     20     30       35      NaN
store2     15      5       10     50.0

In [39]:
print('How many bikes are in each store\n', store['bikes'])

How many bikes are in each store
 store1    20
store2    15
Name: bikes, dtype: int64

In [41]:
print('How many bikes are in store1\n', store['bikes']['store1'])

How many bikes are in store1
 20

In [49]:
print('How many watches and bikes', store[['watches', 'bikes']])

How many watches and bikes in store1         watches  bikes
store1       35     20
store2       10     15

In [51]:
print('How many watches and bikes in store1', store.loc['store1'])

How many watches and bikes in store1 bikes      20.0
pants      30.0
watches    35.0
glasses     NaN
Name: store1, dtype: float64

#### Add a Column to existing DataFram

In [52]:
store['shirts'] = [20,25]
store

        bikes  pants  watches  glasses  shirts
store1     20     30       35      NaN      20
store2     15      5       10     50.0      25

In [53]:
store['jalabiya'] = store['shirts'] + store['pants']
store

        bikes  pants  watches  glasses  shirts  jalabiya
store1     20     30       35      NaN      20        50
store2     15      5       10     50.0      25        30

#### Create a New row and add it to store

In [54]:
new_items = [{'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4}]

In [55]:
new_store = pd.DataFrame(new_items, index=['store3'])
new_store

        bikes  pants  watches  glasses
store3     20     30       35        4

In [60]:
store = pd.concat([store, new_store])
store

        bikes  pants  watches  glasses  shirts  jalabiya
store1     20     30       35      NaN    20.0      50.0
store2     15      5       10     50.0    25.0      30.0
store3     20     30       35      4.0     NaN       NaN
store3     20     30       35      4.0     NaN       NaN
store3     20     30       35      4.0     NaN       NaN

#### Insert

In [70]:
store.insert(4, 'sneakers', [8.5, 9, 8, 7.5, 8])
store

ValueError: cannot insert sneakers, already exists

In [63]:
store.drop(['store3'], axis=0)

        bikes  pants  watches  glasses  sneakers  shirts  jalabiya
store1     20     30       35      NaN       8.5    20.0      50.0
store2     15      5       10     50.0       9.0    25.0      30.0

In [71]:
store

        watches  glasses  sneakers  shirts  jalabiya
store1       35      NaN       8.5    20.0      50.0
store2       10     50.0       9.0    25.0      30.0
store3       35      4.0       8.0     NaN       NaN
store3       35      4.0       7.5     NaN       NaN
store3       35      4.0       8.0     NaN       NaN

In [72]:
store.drop(['bikes', 'pants'], axis=1)

KeyError: "['bikes', 'pants'] not found in axis"

In [73]:
store.rename(index, {'store2': 'store'})

NameError: name 'index' is not defined