In [1]:
import pandas as pd

In [14]:
google_stock = pd.read_csv('./GOOG.csv')

In [15]:
google_stock.shape

(3313, 7)

In [16]:
google_stock

,Date,Open,High,Low,Close,Adj Close,Volume
0,2004-08-19,49.676899,51.693783,47.669952,49.845802,49.845802,44994500
1,2004-08-20,50.178635,54.187561,49.925285,53.805050,53.805050,23005800
2,2004-08-23,55.017166,56.373344,54.172661,54.346527,54.346527,18393200
3,2004-08-24,55.260582,55.439419,51.450363,52.096165,52.096165,15361800
4,2004-08-25,52.140873,53.651051,51.604362,52.657513,52.657513,9257400
...,...,...,...,...,...,...,...
3308,2017-10-09,980.000000,985.424988,976.109985,977.000000,977.000000,891400
3309,2017-10-10,980.000000,981.570007,966.080017,972.599976,972.599976,968400
3310,2017-10-11,973.719971,990.710022,972.250000,989.250000,989.250000,1693300
3311,2017-10-12,987.450012,994.119995,985.000000,987.830017,987.830017,1262400
3312,2017-10-13,992.000000,997.210022,989.000000,989.679993,989.679993,1157700

In [17]:
google_stock.head()

         Date       Open       High        Low      Close  Adj Close    Volume
0  2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1  2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2  2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3  2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4  2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [18]:
google_stock.tail()

,Date,Open,High,Low,Close,Adj Close,Volume
3308,2017-10-09,980.000000,985.424988,976.109985,977.000000,977.000000,891400
3309,2017-10-10,980.000000,981.570007,966.080017,972.599976,972.599976,968400
3310,2017-10-11,973.719971,990.710022,972.250000,989.250000,989.250000,1693300
3311,2017-10-12,987.450012,994.119995,985.000000,987.830017,987.830017,1262400
3312,2017-10-13,992.000000,997.210022,989.000000,989.679993,989.679993,1157700

Find null values

In [19]:
google_stock.isnull().any()

Date         False
Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

See the descriptive statistics of each column

In [20]:
google_stock.describe()

,Open,High,Low,Close,Adj Close,Volume
count,3313.000000,3313.000000,3313.000000,3313.000000,3313.000000,3.313000e+03
mean,380.186092,383.493740,376.519309,380.072458,380.072458,8.038476e+06
std,223.818650,224.974534,222.473232,223.853780,223.853780,8.399521e+06
min,49.274517,50.541279,47.669952,49.681866,49.681866,7.900000e+03
25%,226.556473,228.394516,224.003082,226.407440,226.407440,2.584900e+06
50%,293.312286,295.433502,289.929291,293.029114,293.029114,5.281300e+06
75%,536.650024,540.000000,532.409973,536.690002,536.690002,1.065370e+07
max,992.000000,997.210022,989.000000,989.679993,989.679993,8.276810e+07

For Single Column google_stock['Adj Close'].describe()

In [21]:
google_stock['Adj Close'].describe()

count    3313.000000
mean      380.072458
std       223.853780
min        49.681866
25%       226.407440
50%       293.029114
75%       536.690002
max       989.679993
Name: Adj Close, dtype: float64

In [22]:
google_stock.mean(numeric_only=True)

Open         3.801861e+02
High         3.834937e+02
Low          3.765193e+02
Close        3.800725e+02
Adj Close    3.800725e+02
Volume       8.038476e+06
dtype: float64

In [23]:
google_stock.min()

Date         2004-08-19
Open          49.274517
High          50.541279
Low           47.669952
Close         49.681866
Adj Close     49.681866
Volume             7900
dtype: object

In [24]:
google_stock.max()

Date         2017-10-13
Open              992.0
High         997.210022
Low               989.0
Close        989.679993
Adj Close    989.679993
Volume         82768100
dtype: object

Statistical Operations Correlation

In [26]:
google_stock.corr(numeric_only=True)

               Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.999904  0.999845  0.999745   0.999745 -0.564258
High       0.999904  1.000000  0.999834  0.999868   0.999868 -0.562749
Low        0.999845  0.999834  1.000000  0.999899   0.999899 -0.567007
Close      0.999745  0.999868  0.999899  1.000000   1.000000 -0.564967
Adj Close  0.999745  0.999868  0.999899  1.000000   1.000000 -0.564967
Volume    -0.564258 -0.562749 -0.567007 -0.564967  -0.564967  1.000000

In [31]:
google_stock.groupby(['Volume'])['Date'].sum()

Volume
7900        2014-04-01
10800       2014-03-31
13100       2014-03-27
41300       2014-03-28
147500      2014-04-02
               ...
73517800    2006-03-31
74263500    2004-10-22
77625900    2005-02-14
79388100    2006-02-28
82768100    2006-01-20
Name: Date, Length: 3261, dtype: object

In [33]:
google_stock.groupby(['Date'])['High'].mean()

Date
2004-08-19     51.693783
2004-08-20     54.187561
2004-08-23     56.373344
2004-08-24     55.439419
2004-08-25     53.651051
                 ...
2017-10-09    985.424988
2017-10-10    981.570007
2017-10-11    990.710022
2017-10-12    994.119995
2017-10-13    997.210022
Name: High, Length: 3313, dtype: float64

In [36]:
google_stock.groupby(['Date', 'Open'])['High'].sum()

Date        Open
2004-08-19  49.676899      51.693783
2004-08-20  50.178635      54.187561
2004-08-23  55.017166      56.373344
2004-08-24  55.260582      55.439419
2004-08-25  52.140873      53.651051
                             ...
2017-10-09  980.000000    985.424988
2017-10-10  980.000000    981.570007
2017-10-11  973.719971    990.710022
2017-10-12  987.450012    994.119995
2017-10-13  992.000000    997.210022
Name: High, Length: 3313, dtype: float64

In [41]:
google_stock.groupby(['Date', 'Close'])['Low'].max()

Date        Close
2004-08-19  49.845802      47.669952
2004-08-20  53.805050      49.925285
2004-08-23  54.346527      54.172661
2004-08-24  52.096165      51.450363
2004-08-25  52.657513      51.604362
                             ...
2017-10-09  977.000000    976.109985
2017-10-10  972.599976    966.080017
2017-10-11  989.250000    972.250000
2017-10-12  987.830017    985.000000
2017-10-13  989.679993    989.000000
Name: Low, Length: 3313, dtype: float64