In [1]:
import pandas as pd

In [5]:
items = [{'bikes': 20, 'pants': 30, 'watches': 35, 'shirts': 15, 'shoes':8, 'suits':45},
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5, 'shirts': 2, 'shoes':5, 'suits':7},
          {'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4, 'shoes':10}]

In [8]:
store_items = pd.DataFrame(items, index=['store 1', 'store 2', 'store 3'])
store_items

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

In [9]:
store_items.isnull()

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1  False  False    False   False  False  False     True
store 2  False  False    False   False  False  False    False
store 3  False  False    False    True  False   True    False

In [10]:
find_null_items = store_items.isnull().sum().sum()
print(find_null_items)

3

In [11]:
find_null_items = store_items.isnull().sum()
print(find_null_items)

bikes      0
pants      0
watches    0
shirts     1
shoes      0
suits      1
glasses    1
dtype: int64

In [13]:
print('Number of non-NaN values in the columns of our DataFrame:\n', store_items.count())

Number of non-NaN values in the columns of our DataFrame:
 bikes      3
pants      3
watches    3
shirts     2
shoes      3
suits      2
glasses    2
dtype: int64

#### Removing Nan Values

In [15]:
store_items.dropna(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 2     15      5       10     2.0      5    7.0     50.0

In [16]:
store_items.dropna(axis=1)

         bikes  pants  watches  shoes
store 1     20     30       35      8
store 2     15      5       10      5
store 3     20     30       35     10

#### Substituting Nan Values

In [17]:
store_items.fillna(0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      0.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     0.0     10    0.0      4.0

#### Forward filling

In [19]:
store_items.ffill(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     2.0     10    7.0      4.0

Forward Filling for Columns

In [20]:
store_items.ffill(axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0     45.0
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    35.0   10.0   10.0      4.0

Backward Filling

In [21]:
store_items.bfill(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0     50.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

Backward Filling for Columns

In [22]:
store_items.bfill(axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0      NaN
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    10.0   10.0    4.0      4.0

Noticed Glasses is not filled, that is because there is no item after it that be backward filled

Interpolate

In [24]:
store_items.interpolate(axis=0)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     2.0     10    7.0      4.0

In [25]:
store_items.interpolate(axis=1)

         bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0     45.0
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    22.5   10.0    7.0      4.0